In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=['台北','台中', '台南', '高雄'],
                   columns=['one', 'two', 'three', 'four'])
df

    one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

In [2]:
#drop
df.drop(index=['台北', '高雄'], inplace=True)
df

    one  two  three  four
台中    4    5      6     7
台南    8    9     10    11

In [4]:
scores = np.random.randint(50,101,size=(50, 5))
df = pd.DataFrame(scores,
                  columns=['國文', '英文', '數學', '自然', '社會'],
                  index=[f"學生{i}" for i in range(1, 51)])
df.index.name = '學生'
df.columns.name = '科目'
sum_values = df.sum(axis=1)
mean_values = df.mean(axis=1)
df['總分'] = sum_values
df['平均'] = mean_values
df

科目     國文  英文  數學   自然   社會   總分    平均
學生
學生1    97  77  79   74   85  412  82.4
學生2    92  52  62   85   60  351  70.2
學生3    75  76  79   83   87  400  80.0
學生4    83  64  64   70   54  335  67.0
學生5    74  60  72   80   82  368  73.6
學生6    66  95  91   68   61  381  76.2
學生7    92  92  74   65  100  423  84.6
學生8    63  84  75   63   85  370  74.0
學生9    50  91  76   81   74  372  74.4
學生10   55  62  92   98   74  381  76.2
學生11   96  51  53   56   58  314  62.8
學生12   99  88  50   74   50  361  72.2
學生13   77  54  90   93   70  384  76.8
學生14   57  82  86   99   77  401  80.2
學生15   84  72  50   51   99  356  71.2
學生16   75  78  50   55   72  330  66.0
學生17   55  84  80   75   98  392  78.4
學生18   54  81  81   74   74  364  72.8
學生19  100  50  60   55   67  332  66.4
學生20   75  55  72   73   83  358  71.6
學生21   77  50  91   85   89  392  78.4
學生22   98  61  61   60   57  337  67.4
學生23   74  61  95   69   64  363  72.6
學生24   97  98  68   61   75  399  79.8
學生25   66  82  75   53   67  343  68.6
學生26   85  99  55   69   68  376  75.2
學生27   93  83  87   78   84  425  85.0
學生28   90  72  97   99   97  455  91.0
學生29   95  76  85   96   99  451  90.2
學生30   83  65  61   51   91  351  70.2
學生31   69  92  91   56   95  403  80.6
學生32   62  95  80   60   79  376  75.2
學生33   97  85  74  100   88  444  88.8
學生34   76  94  87   94   73  424  84.8
學生35   81  98  56   90   67  392  78.4
學生36   90  57  69   95   52  363  72.6
學生37   56  76  53   58   61  304  60.8
學生38   51  66  90   58   95  360  72.0
學生39   72  92  51   57   91  363  72.6
學生40   87  75  64   53   54  333  66.6
學生41   97  88  92   64   71  412  82.4
學生42   78  61  71   80   62  352  70.4
學生43   59  90  92   68   82  391  78.2
學生44   74  51  76   84   66  351  70.2
學生45   83  60  57   75   95  370  74.0
學生46   52  72  59   62   70  315  63.0
學生47   98  60  74   65   52  349  69.8
學生48   53  78  97   74   75  377  75.4
學生49   73  91  82   96   69  411  82.2
學生50   71  57  52   74   75  329  65.8

In [ ]:
#排序和排名
#排序rank()
rank_values = sum_values.rank(method='min')
df['排名'] = rank_values
df

科目     國文  英文  數學   自然   社會   總分    平均    排名
學生
學生1    97  77  79   74   85  412  82.4  43.0
學生2    92  52  62   85   60  351  70.2  12.0
學生3    75  76  79   83   87  400  80.0  39.0
學生4    83  64  64   70   54  335  67.0   8.0
學生5    74  60  72   80   82  368  73.6  24.0
學生6    66  95  91   68   61  381  76.2  31.0
學生7    92  92  74   65  100  423  84.6  45.0
學生8    63  84  75   63   85  370  74.0  25.0
學生9    50  91  76   81   74  372  74.4  27.0
學生10   55  62  92   98   74  381  76.2  31.0
學生11   96  51  53   56   58  314  62.8   2.0
學生12   99  88  50   74   50  361  72.2  19.0
學生13   77  54  90   93   70  384  76.8  33.0
學生14   57  82  86   99   77  401  80.2  40.0
學生15   84  72  50   51   99  356  71.2  16.0
學生16   75  78  50   55   72  330  66.0   5.0
學生17   55  84  80   75   98  392  78.4  35.0
學生18   54  81  81   74   74  364  72.8  23.0
學生19  100  50  60   55   67  332  66.4   6.0
學生20   75  55  72   73   83  358  71.6  17.0
學生21   77  50  91   85   89  392  78.4  35.0
學生22   98  61  61   60   57  337  67.4   9.0
學生23   74  61  95   69   64  363  72.6  20.0
學生24   97  98  68   61   75  399  79.8  38.0
學生25   66  82  75   53   67  343  68.6  10.0
學生26   85  99  55   69   68  376  75.2  28.0
學生27   93  83  87   78   84  425  85.0  47.0
學生28   90  72  97   99   97  455  91.0  50.0
學生29   95  76  85   96   99  451  90.2  49.0
學生30   83  65  61   51   91  351  70.2  12.0
學生31   69  92  91   56   95  403  80.6  41.0
學生32   62  95  80   60   79  376  75.2  28.0
學生33   97  85  74  100   88  444  88.8  48.0
學生34   76  94  87   94   73  424  84.8  46.0
學生35   81  98  56   90   67  392  78.4  35.0
學生36   90  57  69   95   52  363  72.6  20.0
學生37   56  76  53   58   61  304  60.8   1.0
學生38   51  66  90   58   95  360  72.0  18.0
學生39   72  92  51   57   91  363  72.6  20.0
學生40   87  75  64   53   54  333  66.6   7.0
學生41   97  88  92   64   71  412  82.4  43.0
學生42   78  61  71   80   62  352  70.4  15.0
學生43   59  90  92   68   82  391  78.2  34.0
學生44   74  51  76   84   66  351  70.2  12.0
學生45   83  60  57   75   95  370  74.0  25.0
學生46   52  72  59   62   70  315  63.0   3.0
學生47   98  60  74   65   52  349  69.8  11.0
學生48   53  78  97   74   75  377  75.4  30.0
學生49   73  91  82   96   69  411  82.2  42.0
學生50   71  57  52   74   75  329  65.8   4.0

In [ ]:
#排名sort_values()
#sort_index
df1 = df.sort_values(by='總分',ascending=True)
df1

科目     國文  英文  數學   自然   社會   總分    平均    排名
學生
學生37   56  76  53   58   61  304  60.8   1.0
學生11   96  51  53   56   58  314  62.8   2.0
學生46   52  72  59   62   70  315  63.0   3.0
學生50   71  57  52   74   75  329  65.8   4.0
學生16   75  78  50   55   72  330  66.0   5.0
學生19  100  50  60   55   67  332  66.4   6.0
學生40   87  75  64   53   54  333  66.6   7.0
學生4    83  64  64   70   54  335  67.0   8.0
學生22   98  61  61   60   57  337  67.4   9.0
學生25   66  82  75   53   67  343  68.6  10.0
學生47   98  60  74   65   52  349  69.8  11.0
學生44   74  51  76   84   66  351  70.2  12.0
學生30   83  65  61   51   91  351  70.2  12.0
學生2    92  52  62   85   60  351  70.2  12.0
學生42   78  61  71   80   62  352  70.4  15.0
學生15   84  72  50   51   99  356  71.2  16.0
學生20   75  55  72   73   83  358  71.6  17.0
學生38   51  66  90   58   95  360  72.0  18.0
學生12   99  88  50   74   50  361  72.2  19.0
學生23   74  61  95   69   64  363  72.6  20.0
學生36   90  57  69   95   52  363  72.6  20.0
學生39   72  92  51   57   91  363  72.6  20.0
學生18   54  81  81   74   74  364  72.8  23.0
學生5    74  60  72   80   82  368  73.6  24.0
學生8    63  84  75   63   85  370  74.0  25.0
學生45   83  60  57   75   95  370  74.0  25.0
學生9    50  91  76   81   74  372  74.4  27.0
學生26   85  99  55   69   68  376  75.2  28.0
學生32   62  95  80   60   79  376  75.2  28.0
學生48   53  78  97   74   75  377  75.4  30.0
學生10   55  62  92   98   74  381  76.2  31.0
學生6    66  95  91   68   61  381  76.2  31.0
學生13   77  54  90   93   70  384  76.8  33.0
學生43   59  90  92   68   82  391  78.2  34.0
學生17   55  84  80   75   98  392  78.4  35.0
學生21   77  50  91   85   89  392  78.4  35.0
學生35   81  98  56   90   67  392  78.4  35.0
學生24   97  98  68   61   75  399  79.8  38.0
學生3    75  76  79   83   87  400  80.0  39.0
學生14   57  82  86   99   77  401  80.2  40.0
學生31   69  92  91   56   95  403  80.6  41.0
學生49   73  91  82   96   69  411  82.2  42.0
學生1    97  77  79   74   85  412  82.4  43.0
學生41   97  88  92   64   71  412  82.4  43.0
學生7    92  92  74   65  100  423  84.6  45.0
學生34   76  94  87   94   73  424  84.8  46.0
學生27   93  83  87   78   84  425  85.0  47.0
學生33   97  85  74  100   88  444  88.8  48.0
學生29   95  76  85   96   99  451  90.2  49.0
學生28   90  72  97   99   97  455  91.0  50.0